"""initial_schema

Revision ID: 83c37152ce79
Revises: 
Create Date: 2026-05-29 15:08:44.052792
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '83c37152ce79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
