"""pitcher_stats_updated_at

Revision ID: d58289de6130
Revises: e41f28a4d96b
Create Date: 2026-05-31 08:33:35.097412
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd58289de6130'
down_revision: Union[str, None] = 'e41f28a4d96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher_stats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'updated_at')
    # ### end Alembic commands ###
