"""p1_standings_batter_pitcher_ext

Revision ID: f05fdb008f76
Revises: 2c5475604bcb
Create Date: 2026-05-30 02:51:29.516381
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f05fdb008f76'
down_revision: Union[str, None] = '2c5475604bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher_stats', sa.Column('games', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('holds', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('home_runs_allowed', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('hbp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_stats', 'hbp')
    op.drop_column('pitcher_stats', 'home_runs_allowed')
    op.drop_column('pitcher_stats', 'holds')
    op.drop_column('pitcher_stats', 'saves')
    op.drop_column('pitcher_stats', 'losses')
    op.drop_column('pitcher_stats', 'wins')
    op.drop_column('pitcher_stats', 'games')
    # ### end Alembic commands ###
