"""players_kbo_id_injury_fields

Revision ID: f86d2d90066c
Revises: 92fa4ac03d7d
Create Date: 2026-05-30 16:08:47.911313
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f86d2d90066c'
down_revision: Union[str, None] = '92fa4ac03d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
