export type GlossaryCategory = "pitcher" | "batter" | "general" | "kbo";

export interface GlossaryTerm {
  abbr: string;          // 약어 (예: ERA)
  korean: string;        // 한글 명칭 (예: 평균자책점)
  full: string;          // 영문 전체 (예: Earned Run Average)
  category: GlossaryCategory;
  formula?: string;      // 계산식
  good?: string;         // 좋은 기준값
  desc: string;          // 상세 설명
  example?: string;      // 예시
  related?: string[];    // 관련 용어
}

export const GLOSSARY: GlossaryTerm[] = [
  // ── 투수 지표 ─────────────────────────────────────────────
  {
    abbr: "ERA",
    korean: "평균자책점",
    full: "Earned Run Average",
    category: "pitcher",
    formula: "(자책점 ÷ 투구 이닝) × 9",
    good: "낮을수록 좋음. 에이스급: 3.00 이하 / 평균: 4.00~4.50 / 부진: 5.00 이상",
    desc: "투수가 9이닝 동안 내준 자책점(수비 실책 제외)의 평균입니다. 투수의 전반적인 능력을 가장 쉽게 파악할 수 있는 지표로, KBO와 MLB 모두에서 핵심 투수 평가 기준으로 활용됩니다. 홈런과 볼넷이 많으면 ERA가 높아지는 경향이 있습니다.",
    example: "ERA 2.81이라면 9이닝 당 2.81점을 내줬다는 의미입니다.",
    related: ["WHIP", "FIP"],
  },
  {
    abbr: "WHIP",
    korean: "이닝당 출루 허용률",
    full: "Walks plus Hits per Inning Pitched",
    category: "pitcher",
    formula: "(볼넷 + 피안타) ÷ 투구 이닝",
    good: "낮을수록 좋음. 1.00 이하 에이스급 / 1.20~1.30 평균 / 1.50 이상 부진",
    desc: "투수가 1이닝 동안 허용한 볼넷과 안타의 합계입니다. 투수가 얼마나 주자를 출루시키는지를 나타내며, ERA보다 운(불규칙한 인플레이 타구 처리)의 영향이 적어 더 안정적인 지표로 평가받습니다.",
    example: "WHIP 1.12라면 1이닝에 평균 1.12명의 주자를 출루시킵니다.",
    related: ["ERA", "BB/9"],
  },
  {
    abbr: "FIP",
    korean: "수비 무관 평균자책점",
    full: "Fielding Independent Pitching",
    category: "pitcher",
    formula: "((홈런×13) + (볼넷+몸에 맞는 공)×3 - 삼진×2) ÷ 이닝 + 상수",
    good: "ERA와 같은 스케일. 낮을수록 좋음",
    desc: "투수가 직접 통제할 수 있는 삼진·볼넷·홈런만으로 계산한 ERA입니다. 수비 실력이나 운(BABIP)의 영향을 제거해 투수 본연의 실력을 더 순수하게 측정합니다. FIP가 ERA보다 낮다면 '운이 나빴던' 투수일 수 있습니다.",
    related: ["ERA", "xFIP"],
  },
  {
    abbr: "K/9",
    korean: "9이닝당 삼진",
    full: "Strikeouts per 9 Innings",
    category: "pitcher",
    formula: "(삼진 ÷ 투구 이닝) × 9",
    good: "높을수록 좋음. 9.0 이상 파워 투수 / 6.0~7.0 평균",
    desc: "9이닝 기준 삼진 아웃을 얼마나 잡는지를 보여줍니다. 삼진은 타자를 가장 확실하게 처리하는 방법으로, K/9가 높은 투수는 위기 상황에서 삼진으로 돌파하는 능력이 뛰어납니다.",
    related: ["BB/9", "K/BB"],
  },
  {
    abbr: "BB/9",
    korean: "9이닝당 볼넷",
    full: "Walks per 9 Innings",
    category: "pitcher",
    formula: "(볼넷 ÷ 투구 이닝) × 9",
    good: "낮을수록 좋음. 2.0 이하 제구 좋음 / 3.5 이상 제구 불안",
    desc: "9이닝 기준 볼넷 허용 수입니다. 볼넷은 공짜로 주자를 내보내는 것으로, BB/9가 높은 투수는 제구력이 불안해 실점 위험이 높습니다. '볼넷은 홈런보다 나쁘다'는 야구 격언도 있습니다.",
    related: ["K/9", "K/BB"],
  },
  {
    abbr: "K/BB",
    korean: "삼진 대 볼넷 비율",
    full: "Strikeout-to-Walk Ratio",
    category: "pitcher",
    formula: "삼진 ÷ 볼넷",
    good: "높을수록 좋음. 3.0 이상 우수 / 2.0 미만 불안정",
    desc: "삼진을 볼넷으로 나눈 값으로 투수의 제구 효율성을 보여줍니다. 값이 높을수록 볼넷은 적게 내주면서 삼진은 많이 잡는다는 의미입니다.",
    related: ["K/9", "BB/9"],
  },
  {
    abbr: "IP",
    korean: "투구 이닝",
    full: "Innings Pitched",
    category: "pitcher",
    formula: "기록은 소수점 형식. 예) 6.2 = 6이닝 2/3",
    good: "선발 투수는 6이닝(QS) 이상이 목표",
    desc: "투수가 아웃카운트를 기록한 총 이닝 수입니다. 1/3이닝 = 아웃 1개, 2/3이닝 = 아웃 2개를 뜻합니다. 기록지에서 '6.2'로 표기되면 6이닝 2아웃을 의미합니다.",
    related: ["QS", "ERA"],
  },
  {
    abbr: "QS",
    korean: "퀄리티 스타트",
    full: "Quality Start",
    category: "pitcher",
    good: "선발 로테이션의 기준. 팀 QS% 높을수록 선발진이 안정적",
    desc: "선발 투수가 6이닝 이상 투구하면서 자책점 3점 이하를 기록한 경기입니다. 팀 승리를 위한 최소한의 '품질 있는 선발 등판' 기준으로 사용됩니다.",
    related: ["ERA", "IP"],
  },
  {
    abbr: "BABIP",
    korean: "인플레이 타구 피안타율",
    full: "Batting Average on Balls In Play",
    category: "pitcher",
    formula: "(피안타 - 피홈런) ÷ (타자 직면 - 삼진 - 피홈런 - 볼넷)",
    good: "리그 평균 .290~.300 수준. 이보다 높으면 운이 나빴을 수 있음",
    desc: "홈런·삼진·볼넷을 제외한 인플레이 타구가 안타가 되는 비율입니다. 투수가 어느 정도 통제할 수 있지만, 수비력과 운에도 크게 좌우됩니다. ERA와 함께 보면 투수의 운 여부를 판단하는 데 유용합니다.",
    related: ["FIP", "ERA"],
  },
  {
    abbr: "HLD",
    korean: "홀드",
    full: "Hold",
    category: "pitcher",
    desc: "구원 투수가 득점권 상황 또는 리드 상황에서 등판해 팀의 리드를 유지하고 물러난 경우에 기록됩니다. 세이브처럼 마무리 투수가 아닌 중간 계투진의 활약을 평가하는 지표입니다.",
    related: ["SV"],
  },
  {
    abbr: "SV",
    korean: "세이브",
    full: "Save",
    category: "pitcher",
    desc: "마무리 투수가 팀의 리드를 지키며 경기를 끝냈을 때 기록됩니다. 3점 이내 리드 상황에서 1이닝 이상 투구하거나, 타이어브레이커 상황에서 3아웃 이상을 잡아야 합니다.",
    related: ["HLD", "BS"],
  },
  {
    abbr: "BS",
    korean: "블론세이브",
    full: "Blown Save",
    category: "pitcher",
    desc: "세이브 기회에서 리드를 잃어버린 경우입니다. 마무리 투수의 신뢰도를 평가하는 역지표로 활용됩니다.",
    related: ["SV"],
  },

  // ── 타자 지표 ─────────────────────────────────────────────
  {
    abbr: "AVG",
    korean: "타율",
    full: "Batting Average",
    category: "batter",
    formula: "안타 ÷ 타수",
    good: ".300 이상 우수 / .280 평균 / .250 미만 부진",
    desc: "타수 대비 안타 비율입니다. 야구에서 가장 오래되고 직관적인 타자 평가 지표입니다. 단, 볼넷·희생플라이는 타수에 포함되지 않으며, 장타력은 반영되지 않습니다. 그래서 현대 야구에서는 OBP·SLG·OPS와 함께 봅니다.",
    example: ".330 타율 = 10번 타석 중 3.3번 안타",
    related: ["OBP", "OPS"],
  },
  {
    abbr: "OBP",
    korean: "출루율",
    full: "On-Base Percentage",
    category: "batter",
    formula: "(안타 + 볼넷 + 몸에 맞는 공) ÷ (타수 + 볼넷 + 몸에 맞는 공 + 희생플라이)",
    good: ".360 이상 우수 / .330 평균 / .300 미만 낮음",
    desc: "타자가 출루하는 모든 방법(안타·볼넷·몸에 맞는 공)을 포함한 출루 비율입니다. 타율보다 타자의 실질적 가치를 더 잘 반영하며, 3아웃을 피하는 능력을 측정합니다.",
    related: ["AVG", "SLG", "OPS"],
  },
  {
    abbr: "SLG",
    korean: "장타율",
    full: "Slugging Percentage",
    category: "batter",
    formula: "(단타 + 2루타×2 + 3루타×3 + 홈런×4) ÷ 타수",
    good: ".450 이상 장거리 타자 / .400 평균 / .350 미만 낮음",
    desc: "타수당 총 루타 수입니다. 단순 타율과 달리 안타의 '종류'를 반영해 홈런 타자에게 더 높은 점수를 줍니다. 장타율 1.000이 이론적 최고값(매 타수 홈런)입니다.",
    related: ["OBP", "OPS", "ISO"],
  },
  {
    abbr: "OPS",
    korean: "출루율 + 장타율",
    full: "On-base Plus Slugging",
    category: "batter",
    formula: "OBP + SLG",
    good: ".900 이상 MVP급 / .800 우수 / .700 평균 / .600 미만 부진",
    desc: "출루율과 장타율을 더한 값으로, 현대 야구에서 타자 종합 능력을 평가하는 가장 대중적인 지표입니다. 계산이 단순하지만 타자의 선구안·파워·컨택 능력을 동시에 반영해 실용성이 높습니다.",
    example: "OBP .360 + SLG .490 = OPS .850",
    related: ["OBP", "SLG", "wOBA"],
  },
  {
    abbr: "ISO",
    korean: "순수 장타율",
    full: "Isolated Power",
    category: "batter",
    formula: "SLG - AVG",
    good: ".200 이상 파워 히터 / .150 평균 / .100 미만 약한 파워",
    desc: "장타율에서 타율을 뺀 값으로 순수한 장타 능력만을 측정합니다. 단타로 인한 타율 영향을 제거해 2루타·3루타·홈런만 반영합니다. ISO가 높은 타자는 중장거리 타자입니다.",
    related: ["SLG", "AVG"],
  },
  {
    abbr: "wOBA",
    korean: "가중 출루율",
    full: "Weighted On-Base Average",
    category: "batter",
    formula: "각 출루 방식에 가중치 적용 후 합산 (볼넷 < 단타 < 2루타 < 3루타 < 홈런)",
    good: ".340 이상 우수 / .310 평균 / .290 미만 부진",
    desc: "단순 OBP와 달리 각 출루 방식의 득점 기여 가중치를 다르게 적용합니다. 통계학적으로 가장 정밀한 타자 종합 평가 지표 중 하나로, 세이버메트릭스(통계 야구학)에서 널리 사용됩니다.",
    related: ["OPS", "wRC+"],
  },
  {
    abbr: "wRC+",
    korean: "가중 득점 생산력",
    full: "Weighted Runs Created Plus",
    category: "batter",
    formula: "리그·구장 보정이 반영된 득점 창출 능력 (리그 평균 = 100)",
    good: "100 이상 평균 이상 / 120 우수 / 150 이상 MVP급",
    desc: "리그 평균과 구장 효과를 보정한 종합 타격 지표입니다. 100이 리그 평균이므로 직관적인 비교가 가능합니다. 예를 들어 wRC+ 130은 리그 평균 타자보다 30% 더 많은 득점에 기여한다는 의미입니다.",
    related: ["wOBA", "OPS"],
  },
  {
    abbr: "BB%",
    korean: "볼넷 비율",
    full: "Walk Percentage",
    category: "batter",
    formula: "볼넷 ÷ 타석 수",
    good: "10% 이상 선구안 우수 / 8% 평균",
    desc: "타석당 볼넷을 얻어내는 비율입니다. 볼넷 비율이 높은 타자는 선구안이 좋고 공을 잘 골라낼 줄 압니다. 상대 투수를 지치게 하고 팀 득점 기회를 만드는 데 크게 기여합니다.",
    related: ["K%", "OBP"],
  },
  {
    abbr: "K%",
    korean: "삼진 비율",
    full: "Strikeout Percentage",
    category: "batter",
    formula: "삼진 ÷ 타석 수",
    good: "낮을수록 좋음. 15% 이하 우수 / 20% 평균 / 25% 이상 약점",
    desc: "타석당 삼진 아웃 당하는 비율입니다. 삼진이 많으면 득점권에서 공격이 끊기는 경우가 많아 팀 공격력을 저하시킵니다. 단, 홈런 타자는 삼진이 많아도 공헌도가 높을 수 있습니다.",
    related: ["BB%", "AVG"],
  },
  {
    abbr: "RBI",
    korean: "타점",
    full: "Runs Batted In",
    category: "batter",
    desc: "타자의 안타·희생플라이·볼넷 등으로 득점한 주자 수입니다. 득점 기여도를 직관적으로 보여주지만, 타순과 팀 득점력에 크게 영향을 받습니다. 3·4번 타자는 득점권 기회가 많아 RBI가 높게 집계됩니다.",
    related: ["AVG", "OPS"],
  },
  {
    abbr: "SB",
    korean: "도루",
    full: "Stolen Base",
    category: "batter",
    desc: "주자가 투구 전 또는 포구 직후 다음 베이스로 성공적으로 이동한 기록입니다. 도루 성공률이 70% 이하라면 도루 시도가 오히려 팀에 불리할 수 있습니다.",
    related: ["CS"],
  },
  {
    abbr: "CS",
    korean: "도루 실패",
    full: "Caught Stealing",
    category: "batter",
    desc: "도루 시도 중 아웃된 횟수입니다. 도루 성공률 = SB ÷ (SB + CS) × 100으로 계산합니다.",
    related: ["SB"],
  },
  {
    abbr: "PA",
    korean: "타석",
    full: "Plate Appearances",
    category: "batter",
    formula: "타수 + 볼넷 + 몸에 맞는 공 + 희생번트 + 희생플라이",
    desc: "타자가 실제로 타석에 들어선 총 횟수입니다. 타수(AB)와 달리 볼넷·희생타도 포함됩니다. 성적 비교 시 최소 타석을 기준으로 삼아 소수 타석의 왜곡을 방지합니다.",
    related: ["AB"],
  },
  {
    abbr: "AB",
    korean: "타수",
    full: "At Bats",
    category: "batter",
    desc: "타석 중 볼넷·몸에 맞는 공·희생타를 제외한 순수 타격 기회입니다. 타율(AVG) 계산의 기준이 됩니다.",
    related: ["PA", "AVG"],
  },

  // ── 일반 / 팀 지표 ────────────────────────────────────────
  {
    abbr: "WAR",
    korean: "대체선수 대비 승리 기여",
    full: "Wins Above Replacement",
    category: "general",
    good: "6.0 이상 MVP급 / 4.0~5.9 올스타 / 2.0~3.9 주전 / 0~1.9 백업",
    desc: "선수가 마이너리그급 대체 선수보다 몇 승을 더 기여했는지를 나타내는 종합 가치 지표입니다. 투수·타자·수비·주루를 통합해 선수 가치를 단일 숫자로 표현합니다. KBO에서는 팬그래프·스탯티즈 등이 자체 WAR를 산출합니다.",
    related: ["wRC+", "FIP"],
  },
  {
    abbr: "LOB%",
    korean: "잔루율",
    full: "Left on Base Percentage",
    category: "pitcher",
    formula: "(볼넷+안타-자책) ÷ (볼넷+안타- 1.5×홈런)",
    good: "70~75% 리그 평균. 과도하게 높거나 낮으면 운 가능성",
    desc: "투수가 만들어낸 주자 중 득점 없이 남겨둔 비율입니다. LOB%가 매우 높다면 실점 없이 운 좋게 위기를 넘긴 것일 수 있고, 낮다면 운이 없었을 수 있습니다.",
    related: ["ERA", "BABIP"],
  },
  {
    abbr: "ELO",
    korean: "ELO 레이팅",
    full: "Elo Rating System",
    category: "kbo",
    good: "1600 이상 강팀 / 1500 평균 / 1400 이하 약팀",
    desc: "체스 마스터 아르파드 엘로가 고안한 상대적 전력 평가 시스템으로 KBO Predictor에서 팀 전력 측정에 활용합니다. 강한 팀을 이기면 많은 점수를 얻고, 약한 팀을 이기면 적은 점수를 얻습니다. 시즌 초 모든 팀은 1500점에서 출발합니다.",
    related: ["파크팩터"],
  },
  {
    abbr: "PF",
    korean: "파크팩터",
    full: "Park Factor",
    category: "kbo",
    formula: "구장별 득점 / 리그 평균 득점 (1.0이 평균)",
    good: "1.05 이상 타자 친화 / 0.95 이하 투수 친화",
    desc: "구장의 특성이 득점 환경에 미치는 영향을 수치화한 지표입니다. 외야가 좁거나 바람이 타자에게 유리하면 1.0 이상, 돔 구장처럼 타구가 덜 날아가면 1.0 미만이 됩니다. KBO Predictor에서는 예비 추정치를 참고용으로 표시하며, 다년 데이터 검증 전까지 승률 계산에는 반영하지 않습니다.",
    related: ["ELO"],
  },
  {
    abbr: "G/F",
    korean: "땅볼/뜬공 비율",
    full: "Ground Ball to Fly Ball Ratio",
    category: "pitcher",
    formula: "땅볼 아웃 ÷ 뜬공 아웃",
    good: "1.5 이상 땅볼 투수 / 1.0 미만 뜬공 투수",
    desc: "투수가 유도하는 타구의 유형을 나타냅니다. 땅볼 투수는 홈런을 잘 허용하지 않지만 내야 안타에 취약하고, 뜬공 투수는 반대 성향을 가집니다. 구장 환경과 함께 고려해야 합니다.",
    related: ["BABIP"],
  },
  {
    abbr: "OAA",
    korean: "평균 대비 아웃 추가",
    full: "Outs Above Average",
    category: "general",
    good: "양수면 평균 이상의 수비, 음수면 평균 이하",
    desc: "수비수가 평균적인 선수보다 얼마나 더 많은 아웃을 만들어냈는지를 나타내는 현대적 수비 지표입니다. KBO에서는 아직 공식 집계가 제한적입니다.",
  },
];

export const CATEGORIES: { id: GlossaryCategory; label: string; icon: string }[] = [
  { id: "pitcher", label: "투수 지표", icon: "⚾" },
  { id: "batter",  label: "타자 지표", icon: "🏏" },
  { id: "general", label: "종합 지표", icon: "📊" },
  { id: "kbo",     label: "KBO Predictor 전용", icon: "🎯" },
];
